name: branches

on:
  push:
    branches: [test-ci]

jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Create local changes
        run: |
          [ ! -f test.txt ] && echo 1 > test.txt
      - name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add test.txt
          git commit -m "add changes from ci"
      - name: Push changes@v0.6.0
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
